/**
 * Report generator — formats analysis results into Markdown.
 */

/**
 * Generate a full Markdown report from PR metadata and analysis results.
 */
export function generateMarkdownReport(metadata, analysis, filterStats) {
  const lines = [];

  // Header
  lines.push(`# 🔍 PR Code Review: #${metadata.number} — ${metadata.title}`);
  lines.push("");
  lines.push(
    `> **Author:** @${metadata.author} | **Branch:** \`${metadata.headBranch}\` → \`${metadata.baseBranch}\` | **Files Changed:** ${metadata.changedFiles} | **+${metadata.additions} / -${metadata.deletions}**`,
  );
  lines.push("");

  // Filter stats
  if (filterStats) {
    lines.push(
      `📁 **Analyzed ${filterStats.keptFiles}/${filterStats.totalFiles} files** (${filterStats.removedFiles} non-code files filtered out)`,
    );
    lines.push("");
  }

  // Summary
  const s = analysis.summary;
  lines.push("## 📊 Summary");
  lines.push("");
  lines.push(
    `| 🔴 Critical | 🟠 High | 🟡 Medium | 🔵 Low | 💡 Info | **Total** |`,
  );
  lines.push(
    `|:-----------:|:-------:|:---------:|:------:|:-------:|:---------:|`,
  );
  lines.push(
    `| ${s.critical} | ${s.high} | ${s.medium} | ${s.low} | ${s.info} | **${s.totalIssues}** |`,
  );
  lines.push("");

  // Phase A: Breaking Bugs
  lines.push("---");
  lines.push("## 🐛 Phase A: Breaking Bugs");
  lines.push("");
  if (analysis.breakingBugs.length === 0) {
    lines.push("✅ **No breaking bugs found!** The code looks solid.");
  } else {
    lines.push("| Severity | File | Title | Description | Suggestion |");
    lines.push("|:--------:|:-----|:------|:------------|:-----------|");
    for (const f of analysis.breakingBugs) {
      const sev = f.severity === "critical" ? "🔴 Critical" : "🟠 High";
      lines.push(
        `| ${sev} | \`${f.file}\` | ${f.title} | ${esc(f.description)} | ${esc(f.suggestion)} |`,
      );
    }
  }
  lines.push("");

  // Phase B: Code Smells
  lines.push("---");
  lines.push("## 🧹 Phase B: Code Smells");
  lines.push("");
  if (analysis.codeSmells.length === 0) {
    lines.push(
      "✅ **No code smells detected!** Clean code practices observed.",
    );
  } else {
    lines.push("| Severity | File | Title | Description | Suggestion |");
    lines.push("|:--------:|:-----|:------|:------------|:-----------|");
    for (const f of analysis.codeSmells) {
      const sev = f.severity === "medium" ? "🟡 Medium" : "🔵 Low";
      lines.push(
        `| ${sev} | \`${f.file}\` | ${f.title} | ${esc(f.description)} | ${esc(f.suggestion)} |`,
      );
    }
  }
  lines.push("");

  // Phase C: Vibe Refactor
  lines.push("---");
  lines.push("## ✨ Phase C: Vibe Refactor");
  lines.push("");
  if (analysis.vibeRefactor.length === 0) {
    lines.push("✅ **Already vibing!** No modernization suggestions needed.");
  } else {
    lines.push("| File | Title | Description | Suggestion |");
    lines.push("|:-----|:------|:------------|:-----------|");
    for (const f of analysis.vibeRefactor) {
      lines.push(
        `| \`${f.file}\` | ${f.title} | ${esc(f.description)} | ${esc(f.suggestion)} |`,
      );
    }
  }
  lines.push("");

  // Footer
  lines.push("---");
  lines.push(`*Generated by PR Review Bot 🤖 at ${new Date().toISOString()}*`);

  return lines.join("\n");
}

/**
 * Escape pipe characters and newlines for Markdown table cells.
 */
function esc(text) {
  if (!text) return "";
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ").replace(/\r/g, "");
}
